### ISSUE TITLE
Add issues for 1.4.0

### ISSUE THREAD

**Issue by rautesamtr** [dolezsa/thermal_comfort#100]
Hi since 1.4.0 release has to be coordinated between one more person i created a 1.4.0 milestone.
@IATkachenko please add any issue/feature you would like to contribute before 1.4.0 especially in regard of config_flow.

**Comment by IATkachenko** [comment]
Hi.

I'm going to make feature for selecting temperature and pressure device from device registry, but it may delay 1.4.0. It is optional now, and I'm not sure that 1.4.0 should wait it.

**Comment by rautesamtr** [comment]
Just add it for now, we can always postpone it. I'd happy if config flow gets polished a bit more for 1.4.0.

**Comment by IATkachenko** [comment]
Looks like simple solution is not good enough: 
 * if I create list based on entity registry, then it broke all tests, because registry is empty while tests and I don't know (now) how to add data to it;
 * this list contain sensors like "absolute humidity" and "feel like temperature". This sensors could not be filtered (by unit of measurements or any other way);
 * this block using sensors out of registry, because UI could not draw `vol.Required(...): vol.Or(vol.In([..]), str))`, but is is legal from Schema point of view (and pass all tests).

Changes is in the [local branch](https://github.com/IATkachenko/thermal_comfort/tree/sensors_list), but now I'm not sure that selection from list should be added.
