### ISSUE TITLE
Add sanity checks for temperature and humidity values

### ISSUE THREAD

**Issue by lymanepp** [dolezsa/thermal_comfort#128]
Occasionally I get spurious temperature and humidity values from my sensors. I don't know if Z-Wave JS or the sensor is to blame. The values are several orders of magnitude higher than they should be, so my graphs are messed up until the bogus data ages off.

It makes sense (to me) to discard humidity values outside the range of 0-100 and temperatures outside the range of lowest and highest temperatures ever recorded on earth. Or something along those lines.
* -89.2 °C -- https://en.wikipedia.org/wiki/Lowest_temperature_recorded_on_Earth
* +56.7 °C -- https://en.wikipedia.org/wiki/Highest_temperature_recorded_on_Earth

Thoughts?

**Comment by rautesamtr** [comment]
Aren't there any sanity checks done in core? Personally i think a lot of this should already be checked in core and updates to invalid values e.g. humidity values outside of the normal percentage range should never be recorded and updated there. Also since this sounds like some kind of quirk of your devices or platform isn't such thing usually handled there first?

Let's get a better picture of the situation in core regarding this issue.

But it makes sense to add some sanity check in thermal comfort since some of the calculations don't even output valid results outside of certain ranges and we should at least log some warning.

**Comment by lymanepp** [comment]
Thanks for fixing!
