### ISSUE TITLE
Not calculating right

### ISSUE THREAD

**Issue by Traxeronus** [dolezsa/thermal_comfort#217]
Hi,

I see Simmer values exactly same as input sensor values. 

![Screenshot 2022-11-11 183954](https://user-images.githubusercontent.com/114311249/201400370-19fef508-8005-46d6-a258-be14069bb9eb.png)

Should be 22.7 for floor 1 and 10.8 for floor 2.

**Comment by matze338** [comment]
I recognaice exactly the same issue :/

**Comment by vaandefanel** [comment]
Same issue too.

**Comment by rautesamtr** [comment]
Currently ssi is not really calculated if bellow 70°F since it's meant for higher temperatures.

https://github.com/dolezsa/thermal_comfort/blob/90a797669a63abc49a0b46bb821b9eba9ee91772/custom_components/thermal_comfort/sensor.py#L869-L884

Not my code but it's a good idea to discuss how to handle such situations in this issue.

**Comment by Traxeronus** [comment]
Hi,
I'm bit lost why? 70F is standard room temperature and when I try to calculate it using some of ssi calculators (f.e. https://www.vcalc.com/wiki/rklarsen/Summer+Simmer+Index), it shows me the right value.
There should be no temp limitation.
Or am I mistaking?
M.

**Comment by rautesamtr** [comment]
@lymanepp do you remember why you added the temp limit?

**Comment by lymanepp** [comment]
I changed my local copy to use 58° F as the cutoff value and it looks much better as the SSI and air temperature converge together at that temperature. No more big jump at 70° F.

**Comment by lymanepp** [comment]
This issue was changed and integrated a while again and can be closed.
