### ISSUE TITLE
Problems comparing values: Absolute humidity "above 10"

### ISSUE THREAD

**Issue by ghulmarduk** [dolezsa/thermal_comfort#291]
I don´t know if this is the fault of the integration or my script calling it´s values; if the value of "absolute humidity" reaches 10, it´s counted less than that (?). 

e.g. at this moment the absolute humidity in my garden is 13,9 g/m³ and in my cellar 9,8 g/m³, but my script outputs a "True" though it should be a "False". When absolute humidity in my garden is below 10 everything works as intended.

this is the script:
`{% if states('sensor.keller_absolute_humidity') > states('sensor.aussen_absolute_humidity')  %}
true
{% else %}
false
{% endif %}`

and this is the entry in my configuration.yaml:
`thermal_comfort:
  - custom_icons: true
    sensor:
    - name: Aussen
      poll: true
      temperature_sensor: sensor.netatmo_heidburg_indoor_draussen_temperature
      humidity_sensor: sensor.netatmo_heidburg_indoor_draussen_humidity
      sensor_types:
        - absolute_humidity
      unique_id: beaf27f0-a57f-4abf-ae26-95043f519951
    - name: Keller
      poll: true
      temperature_sensor: sensor.heidburg_keller_temperature
      humidity_sensor: sensor.heidburg_keller_humidity
      sensor_types:
        - absolute_humidity
      unique_id: 0740910d-5d43-451a-9aa0-54c815e74ee1`

**Comment by ghulmarduk** [comment]
Update: the absolute humidity in my cellar just went up to 10,2 g/m³ and the script outputs a "False" as intended.

**Comment by RonnyAL** [comment]
This is happening because you're comparing the values as strings. This leads to "alphabetical" sorting, where 0 comes before 3. You can solve it by parsing the values properly, like so:

`{% if states('sensor.keller_absolute_humidity') | float > states('sensor.aussen_absolute_humidity') | float %} true {% else %} false {% endif %}`

Furthermore, you're essentially saying `{% if true %}true{% else %}false{% endif %}` which is unnecessary. The following would suffice: `{% states('sensor.keller_absolute_humidity') | float > states('sensor.aussen_absolute_humidity') | float %} `.

**Comment by ghulmarduk** [comment]
Thank you so much - i´ll try that out.
