### ISSUE TITLE
new feature request : add freezing point and frost risk level

### ISSUE THREAD

**Issue by papo-o** [dolezsa/thermal_comfort#36]
hello, 
can you add freezing point and frost risk level at this nice component?
the  freezing point function 
```
def computeFreezingPoint(self, temperature, humidity):
        """ https://pon.fr/dzvents-alerte-givre-et-calcul-humidite-absolue/ """
        dewPoint = self.computeDewPoint(temperature, humidity)
        T = temperature + 273.15
        Td = dewPoint + 273.15
        return round((Td + (2671.02 /((2954.61/T) + 2.193665 * math.log(T) - 13.3448))-T)-273.15,2)

```
the risk level function

```
    def computeRiskLevel(self, temperature, humidity):
        thresholdAbsHumidity = 2.8
        dewPoint = self.computeDewPoint(temperature, humidity)
        absoluteHumidity = self.computeAbsoluteHumidity(temperature, humidity)
        freezePoint = self.computeFreezingPoint(temperature, humidity)
        if temperature <= 1 and freezePoint <= 0 and absoluteHumidity < thresholdAbsHumidity:
            return 1 # Frost unlikely despite the temperature Givre peu probable malgré la température
        elif temperature <= 4 and freezePoint <= 0.5 and absoluteHumidity > thresholdAbsHumidity:
            return 2 # Frost probable despite the temperature Givre probable malgré la température
        elif temperature <= 1 and freezePoint <= 0 and absoluteHumidity > thresholdAbsHumidity:
            return 3 # high probability of frost Présence de givre
        return 0 # No risk of frost Aucun risque de givre

```

**Comment by Torgrima** [comment]
This is a fantastic idea and at the same time give critical coldspot warning for mold/fungus. I hope thermal_comfort will be a part of home-assitant core one day :) 

Home-assistant has a mold sensor for today: 
https://www.home-assistant.io/integrations/mold_indicator/

For calibration you must use a IR thermometer or Thermo camera to give the lowest temperature in the room. e.g old window frames, behind a curtans, behind the coutch...

A calibration method could be to give two temperature readings when no heat/cold source is used in the room, to also calculate "Thermal transmittance".

Thermal transmittance, also known as U-value, is the rate of transfer of heat through a structure (which can be a single material or a composite), divided by the difference in temperature across that structure. The units of measurement are W/m²K.

**Comment by rautesamtr** [comment]
I will look into this. Could you explain to me how the freezing point is to be read/interpreted? How is this used in home automation? Is this used to prevent frost damage on building or/and frost protection of plants with sprinklers?
I understand the dew point but can't just grasp yet the meaning of the freezing point. I know the common 0°C water freezes in normal conditions water freezing point.
e.g. this freezing point would be 10.43°C with a temperature of 25°C and 50% relative humidity. I guess that the reading probably isn't of any interest at such high ambient temperature?
I just would like to get a proper grasp of something before implementing it.
Do you think this should be part of the default sensors or explicitly enabled?

**Comment by papo-o** [comment]
Hello,
I am currently using it with a fork (frost risk) of an old version of this git.
I use it to predict the frost on my car window with two devices. an exterior probe as close as possible to my car and a Darksky forecast 12 hours .
I programmed two automations to notify me the night before (at 6:00 p.m.) with darksky prevision and in the morning (at 7:00 a.m.)with the exterior probe  to defrost the car window before going to work

**Comment by Torgrima** [comment]
A sensor for "room health preseption", will be very useful, anywhere in the world, where the temperatur is below 3℃. 
Or where there is a big diffrence in temperature from the outisde. e.g because of air conditioning or good isolation (U value). 

When the temperature diffrence on the wall compared to the cold side is large, there is a high probobility for "dew spotts" or risk of "frost spots" in some parts of the room. 
E.g I have 7℃ diffrence from my temperature sensor in one of the windows, this comes as coldspotts in the thermo camera. 
Samples of a simular problem: 
https://www.jaredwatkins.com/pics/thermal_guestWindow.jpg
https://www.jaredwatkins.com/pics/thermal_mediaWall.jpg 

- E.g if you travel and your cabin or house is unatended for several month during the year, you would like to get a "alarm" if some cold spots in the room gets below x number of ℃ below dewPoint   .

You will get a risk for mold/fungi where the room gets below dewPoint, and there is slow evaperation repitingly. 
https://www.ecofmr.com/articles/wp-content/uploads/2020/12/window-mold.jpg

- Same with the car windows in the morning It would be nice to have a alarm telling that there is a high probobility that you need to go out and scrape ice, or apply a heat source/ventelation to prevent it. 

- If you have a cabin or travel for longer periods it would be greate to get notified for mold or frost risk.

To predict if there will be dew on the inside or outside of a cold spott or a window. 
The code will need to compare two different sensors, the cold side with the hot side e.g:
https://github.com/home-assistant/core/tree/dev/homeassistant/components/mold_indicator

**Comment by rautesamtr** [comment]
I understand the dew point and the relevance for dew and hence for mold/frost.
What i didn't understand was how to interpret the value calculated by `calulateFreezingPoint`.
I finally found is this [site](https://www.weather.gov/source/zhu/ZHU_Training_Page/fog_stuff/Dew_Frost/Dew_Frost.htm#FROST3) describing a "frost point". Is this it? So if i understand this correctly the "dew point" is relevant for surfaces that are above 0°C resulting in dew. The "frost point" gets relevant for surfaces that are around or bellow 0°C. The frost point resides between current temperature and dew point because ice surfaces attract dew more easily then non ice surfaces and the temperature turns the dew immediately to frost.
Is this understanding correct?

**Comment by papo-o** [comment]
I think. since the installation on my system, there are few false positives

**Comment by Torgrima** [comment]
Greate article, well described and I can related by experience.

It would be really nice if one instance of thermal comfort, could have multiple "dew or frost point sensors", based on a temperature offset. 

As described in the article, a surface temperature in one spot can be diffrent by several degrees in close proximity, depending on the surface type and isolation.

**Comment by rautesamtr** [comment]
@papo-o 
Question regarding the frost risk calculation:
```python
…
        elif temperature <= 4 and freezePoint <= 0.5 and absoluteHumidity > thresholdAbsHumidity:
            return 2 # Frost probable despite the temperature Givre probable malgré la température
        elif temperature <= 1 and freezePoint <= 0 and absoluteHumidity > thresholdAbsHumidity:
            return 3 # high probability of frost Présence de givre
…
```
Is this order intended?
Because in most cases this will result in a frost risk of level 2 and not 3?
Or should we check for frost level 3 before frost level 2?

**Comment by papo-o** [comment]
You are right 
We can check for frost level 3 before frost level 2

**Comment by Torgrima** [comment]
Just wanted to give a good illustration from today's outside temperature with ice on the car window, even when the outside temperature is 2.9ºC and Dew Point estimated to be 0,23ºC

 
https://photos.app.goo.gl/DD6JjC3CemSSayy9A

**Comment by rautesamtr** [comment]
> It would be really nice if one instance of thermal comfort, could have multiple "dew or frost point sensors", based on a temperature offset.

Couldn't you just use template sensors applying an offset and them as input for thermal_comfort sensors?

**Comment by Torgrima** [comment]
I do that today based on the dew point value.

To get a userfriendly version for every one, it would be grate if it was a sensor created from thermal_comfort, where the user can spesify a fridenly_name and a offset_temperature for the "dew or frost point sensors". 
Standard offset can be 3℃ lower then the input temperature sensor.
 
If you don't have a thermal camera or IR termometer you would probobly not notice that you have potential multible problemspots in the room. 

I have diffrent cold spots in the room e.g a window frame and a cold spot in a corner of the room with two diffrent offsets. The offset is 7℃ for the window frame and 4℃ for a corner. Both generate condensation at diffrent times if I don't start air circulation or increase heat.  

That is why it would be nice if those coldspots is represented as diffrent sensors.

**Comment by Torgrima** [comment]
I am trying to understand the values in the computeFreezingPoint function. 
The only one I understand is 0 degrees Celsius is equal to 273.15 degrees Kelvin. What does the other constants represent? 

`round((Td + (2671.02 /((2954.61/T) + 2.193665 * math.log(T) - 13.3448))-T)-273.15,2)` 

- Calibration
If the sensor does not include a calibration value for a temperature offset, I think you will get a lot of false readings. 

I get different numbers from the local weather forecast, my temperature at ground level, air temperature and on the diffrent surfaces that has diffrent "thermal transmittance (U-value)"
https://en.wikipedia.org/wiki/Thermal_transmittance 
Inside a building, the heat transfer/thermal conductivity will be important also.
https://en.wikipedia.org/wiki/Thermal_conductivity 

- Freezing-point on a Surface will depend on how well it reflect/absorbe, transmitt heat.Therefore it is diffrent for e.g Glas, Concreate,  foam glass, tiles, wood, asphalt, frutes... so my quiestion is what is the sensor calibrated for, is this one of the constants? 

**I think the sensor is a greate idea, but to get more value out of the sensor would have been to  predict, the diffrent "Phase changes" of a given surface.**

_My bigg question is when and for how long, is the surface in a given state._ 
E.g in a bathrom window where the outside temp is -20°C and the inside is +20°C:

-  dry to moist
-  moist to dropplets 
-  droplets to solid
-  frost point 

It is the number of times and the number of minuts the surface is in a given state, that is important if you want to assest the risk for maintnance reduction and automation of clima settings, optimice for power cost. 

e.g if you want to predict: mold/fungi, ice, frost depth prediction, heating, ventilasjonrequirments...

This is a interesting article: "Calibration and development of a
numerical method for frost protection"
https://vegvesen.brage.unit.no/vegvesen-xmlui/bitstream/handle/11250/2621579/Masteroppgave_%20Iris%20Kristin%20Koa_2019.pdf?sequence=1&isAllowed=y

**Comment by papo-o** [comment]
The temperature of the icing point is greater than that of the dew point because the saturated vapor pressure of ice is lower than that of water1. When we know the dew point, we can calculate the icing point in kelvin as follows (applicable only if the temperature is below the freezing point of 0 ° C, i.e. 273.15 [K)]:
(https://fr.wikipedia.org/wiki/Point_de_givrage)

**Comment by Torgrima** [comment]
Yes, I read the article and tried to find the source for the equation and the constants used. But it differ from other frost equetions. 

e.g: Atmospheric Thermodynamics:  [https://www.ewingdigital.com/text_content/paper%20-%203%20(%20unit%20-%203)15895537055ebeaa2940247.pdf](url)

Freezing-point depression
[https://en.wikipedia.org/wiki/Freezing-point_depression ](url)

Freezing point METEOROLOGIST JEFF HABY
[https://www.weather.gov/source/zhu/ZHU_Training_Page/fog_stuff/Dew_Frost/Dew_Frost.htm#FROST3](url)

Online freezing-point-depression calculator 
[https://www.omnicalculator.com/chemistry/freezing-point-depression](url)

**Comment by Torgrima** [comment]
I still havn't found other articles with the same constants as computeFreezingPoint uses, but I think I understand the concept better. 
If the function includes both the wet-bulb temperature and the surface temperature. 

**Icing point** = is when **a** seed (dust or a particel) in the air or a **given surface** like the car window, **gets equal** or below the **freezing point** of the water that is saturated the **air's** "**wet-bulb temperature**". 
When the web-bulb temperature gets below the same temperatur, you get Ice crystals growing on the surface. 
When this happen in mid air, you get snow. 

An other important factor regarding wet-bulb temperature regarding human comfort, is that a humans can only selfregulate heat and cooling within a "narrow" wet-bulb temperature window. 

I don't want to quate a spesific number, because I have read several values, but it is in the range of 24°C - 34°C. 
 
This [online calculator](https://www.omnicalculator.com/physics/wet-bulb) might illustrate a wet-bulb temperature goes below freesing when the regular dry-bulb temperature is several degrees abow freesing, depending on relative humidity.

**Comment by Plawasan** [comment]
Just a nitpick for the new sensors - device_class has a duplicate underscore:

```
DEVICE_CLASS_THERMAL_PERCEPTION ='thermal_comfort__thermal_perception'
DEVICE_CLASS_FROST_RISK = 'thermal_comfort__frost_risk'
```

**Comment by rautesamtr** [comment]
> Just a nitpick for the new sensors - device_class has a duplicate underscore:
> 
> ```
> DEVICE_CLASS_THERMAL_PERCEPTION ='thermal_comfort__thermal_perception'
> DEVICE_CLASS_FROST_RISK = 'thermal_comfort__frost_risk'
> ```

https://github.com/home-assistant/core/blob/512a474e934798c0bd2bdf5860bf5a56956045e5/script/hassfest/translations.py#L205

**Comment by Plawasan** [comment]
> > Just a nitpick for the new sensors - device_class has a duplicate underscore:
> > ```
> > DEVICE_CLASS_THERMAL_PERCEPTION ='thermal_comfort__thermal_perception'
> > DEVICE_CLASS_FROST_RISK = 'thermal_comfort__frost_risk'
> > ```
> 
> https://github.com/home-assistant/core/blob/512a474e934798c0bd2bdf5860bf5a56956045e5/script/hassfest/translations.py#L205

I've learned something today.. it still bothers me but now I understand why :) Thanks..

**Comment by rautesamtr** [comment]
@papo-o
Are you satisfied with the current implementation? Is this issue ok to close?

@Torgrima 
I appreciate your enthusiasm, as it also helped me to get a better grasp. For now I pushed forward to implement papo-o's formula to have a simple implementation for the sensor for now. If it is important for you we can look into refining or replacing this with a better version at some point. Especially if the current version results in too many false positives. Regarding input offset we could probably look into adding template_input at some point, but I would prefer if separate issues would be opened for different feature requests.

**Comment by papo-o** [comment]
Yes
thanks
