### ISSUE TITLE
Feature Request: Setup new sensors on frontend

### ISSUE THREAD

**Issue by patrickhilker** [dolezsa/thermal_comfort#73]
It would be super awesome to be able to setup new sensors using the home assistant frontend, just as this is possible with other integrations. 

I would expect to install this repo and then go to the integration page and click "new integration". There I would expect to select this integration and further choose a name, select a temperature sensor and a humidity sensor. After this the corresponding sensor would be created automatically.

This could be repeated for every sensor.

Pro: It would not be needed to configure them by yaml anymore. 👍🏻

**Comment by rautesamtr** [comment]
This is on my roadmap. The downside is, that you are going to have to set up each pair as an extra integration since as a custom integration we are restricted to the simple options menu. Everything else would need a seperate frontend as custom integration.

**Comment by patrickhilker** [comment]
Awesome! As I don't know any details on the home assistant architecture: Is this a big impact? I already know this from the (core) shelly and (core) tp-link kasa integration and for me it seems to be pretty normal.

Thank you for your effort!

**Comment by rautesamtr** [comment]
To implement basic support isn't that much of an effort. I allready had a basic prototype with this feature running but gave up on it because of the frontend UI restrictions for custom integrations. I would have prefered some nice custom config pages like for example ZHA. Theres some things i still have to make up my mind how to handle them. And right now i have other priorities like getting the code in better shape to make it possible to upstream it should the chance ever arrise.

But i understand the comfort of having the possibility to configure this in the frontend, also making this more accesable for non tech users. So i definitly want to see this happen sooner then later. Probably will work on this once i refactored the code and moved to [modern hass yaml config](https://github.com/home-assistant/architecture/blob/master/adr/0007-integration-config-yaml-structure.md#decision).
