### ISSUE TITLE
Platform error sensor.thermal_comfort - Integration 'thermal_comfort' not found.

### ISSUE THREAD

**Issue by ralphhughes** [dolezsa/thermal_comfort#9]
I have copied your example from the "Usage" section of the readme. There doesn't seem to be a section in the readme for installation but with other custom components they say to download the project ZIP from github and copy the zip contents to the "config/custom_components/" folder, creating "custom_components" if necessary. 

I have done this and still get the error
"Platform error sensor.thermal_comfort - Integration 'thermal_comfort' not found." after restarting home assistant. Is there something else I need to do?

(I am using Home Assistant 0.114.4 on a Raspberry Pi 3)

**Comment by wipeout666** [comment]
Same issue, but I'm a newbie, so that may be normal :)

**Comment by wipeout666** [comment]
FYI, I made it work by doing that:

When downloading a custom_component after 0.94:

in the directory for that integration you need at least 2(3) files.
A _init__.py file (This can be blank/contain only a docstring if the integration only are a platfrom).
A manifest.json 63 file.
The platform files (sensor/switch and so on.)
After you have downloaded them and placed them in the correct directory, restart HA.
After the restart add it to your config.
Run config_check.
Restart HA.

From: post #10 https://community.home-assistant.io/t/custom-components-not-working-since-0-94-2/122779/9
